POST http://localhost:5000/myFlights
content-type: application/json

{
"flight_id":"61c34611f22b52facd5b07a2",
 "token": "eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MWQ1ZDI4YWU5YTY4YmJlYmY0NDZiOTgiLCJlbWFpbCI6Imtva29AZW1haWwuY29tIiwicGFzc3dvcmQiOiJrb2tvIiwiZmlyc3RfbmFtZSI6Imtva28iLCJsYXN0X25hbWUiOiJrb2tvIiwiY29udHJ5X2NvZGUiOiJrb2tvIiwidGVsZXBob25lX251bWJlciI6IjEyMyIsImZsaWdodHNJRCI6IjYxYzBhNDUwMjhmOTExYzhiOTk2YzJkMCw2MWMwYTRhOTVkMmViN2E1MGNkN2M4N2MiLCJ0aWNrZXRzSUQiOiIiLCJfX3YiOjB9.S0aTPCp4WDB-gKhzDO9PGRTGbI_nGrSv1E6kYUTvYOI"
 }