# here we test if a non logged in user tries to answer

POST http://localhost:5000/myFlights
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MWQ1ZDI4YWU5YTY4YmJlYmY0NDZiOTgiLCJlbWFpbCI6Imtva29AZW1haWwuY29tIiwicGFzc3dvcmQiOiJrb2tvIiwiZmlyc3RfbmFtZSI6Imtva28iLCJsYXN0X25hbWUiOiJrb2tvIiwiY29udHJ5X2NvZGUiOiJrb2tvIiwidGVsZXBob25lX251bWJlciI6IjEyMyIsImZsaWdodHNJRCI6IjYxYzBhNDUwMjhmOTExYzhiOTk2YzJkMCw2MWMwYTRhOTVkMmViN2E1MGNkN2M4N2MsNjFjMzQ2MTFmMjJiNTJmYWNkNWIwN2EyIiwidGlja2V0c0lEIjoiIiwiX192IjowfQ.AuHQ49kfxxCKBQvnJeKU-0ftO6v0hoOjFEzKVJYv9o8"
}
###
# test when logged in user

POST http://localhost:5000/LoginUser
content-type: application/json

{
    "email": "koko@email.com",
    "password": "koko"
}
