POST http://localhost:5000/LoginUser
content-type: application/json

{
    "username":"a",
    "password":"a",
    "token":"eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MWRmZjk1YTNmZmIxMGM0NzNiYWMwMGQiLCJlbWFpbCI6ImEiLCJwYXNzd29yZCI6ImEiLCJuaWNrbmFtZSI6ImxvbG8iLCJmaXJzdF9uYW1lIjoiZmlyc3QiLCJsYXN0X25hbWUiOiJsYXN0IiwiaG9tZV9hZGRyZXNzIjoiQmVybGluIiwiY29udHJ5X2NvZGUiOiJlZ3lwdCIsInRlbGVwaG9uZV9udW1iZXIiOiIxMjM0NTYiLCJwYXNzcG9ydCI6IkE1NiIsImZsaWdodHNJRCI6W10sInRpY2tldHNJRCI6W10sIl9fdiI6MH0.8HmpUgiNpHS4xeo5aci15NEBPdF6eymIeNUW8tY7M6I"
}